{% set version = "0.8.3" %}

package:
  name: s-tui
  version: {{ version }}

source:
  url: https://github.com/amanusk/s-tui/archive/v{{ version }}.tar.gz
  sha256: 74270fe57b3350f0cfa1a9f0fba80951d2117d7284de509863dbeadfcdbd78dc

build:
  number: 0
  # urwid not available for windows
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - urwid >=1.3.1
    - psutil >=5.2.0

test:
  imports:
    - s_tui

about:
  home: https://github.com/amanusk/s-tui
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: "Stress Terminal UI stress test and monitoring tool"
  description: |
      s-tui is a terminal UI for monitoring your computer. s-tui allows to
      monitor CPU temperature, frequency, power and utilization in a graphical
      way from the terminal.
  doc_url: https://amanusk.github.io/s-tui
  dev_url: https://github.com/amanusk/s-tui

extra:
  recipe-maintainers:
    - ericdill
