{% set version = "1.1.4" %}

package:
  name: s-tui
  version: {{ version }}

source:
  
  url: https://github.com/amanusk/s-tui/archive/v{{ version }}.tar.gz
  sha256: aeebcf7b04beb8526c98d675ae2b2f106fd1e00343b0c37c78b4a84c31561d0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - s-tui = s_tui.s_tui:main

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - urwid >=2.0.1
    - psutil >=5.9.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - s_tui

about:
  home: https://github.com/amanusk/s-tui
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Stress Terminal UI stress test and monitoring tool
  description: |
    s-tui is a terminal UI for monitoring your computer. s-tui allows to
    monitor CPU temperature, frequency, power and utilization in a graphical
    way from the terminal.
  doc_url: https://amanusk.github.io/s-tui
  dev_url: https://github.com/amanusk/s-tui

extra:
  recipe-maintainers:
    - ericdill
