travis:
  secure:
    BINSTAR_TOKEN: MLpqTR9bpzj0jYjKIubRN5PP8AbTnraU2gJCBUcQt4b+jdJ08XkKzAqImP6TNqtvjhOAe2c2UogkXcHcyDDYCgrNjHMYCOTXUGGprruN89ubFlvuX7EL3J4PKpVHEx2ydHLCtqFTxlzkJroX4fM5lmBiGjwxdWTh0rDv4igZpVThsLqZwciQgfL3tY4xoG2HT9AyblG2fIBekAtJuxQxNuPMD0yA+hRSGeQuIlqi/sxY5K4noL97v9D72Z0a7qKDuJMxPjQ9KCYCnIZaurNxmt7YS4IG5QAJ4oDv3+F9evh62L7JG2xHGS+RuVgvwuYIu9u517tFd7HoAm8HJasgpTvLF6kihTWzs1cN57qvHzD7n1x+10sGmbPfIPRrddIVfUrUbMK+CDqIhB3gM10l6SJS1pP71rFKbKXOAxMuUdaFNoVPJqaNquAxptJcYvOA5R7aTo+HiEeHM2EQ4scxmKPNtiwhSJ/klxG+hL68+UnVvPbUtXD+tqWV97BwPb4EizLrQp+ftXiHSocAOJsEf6KyvYMJhbFbT7YRtjkN3gAWDtnrFQNUgkih0B2/xVNpx0MnIRKOwNCha93PvKg4T22MnpSMUa9CmXJrnFROn+PCmbwyCLaqb4cVMl2dyh+tOUu1+7TSBET9DcWNmMmb62qNJFRoonnc1UaG2vERF2g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
